language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: build
      install:
        - npm install 

      addons:
        sonarcloud:
          organization: "manelcecs"
          token:
            secure: gQQYvxvKt3PzChIfV0zHDDGb3dBTNhljPfKf44bH0KjFLa8zzqKK3dHg8BHQncdaGFXIPrqb9ME0xHxf+sGTZv5K1YNoVuaLuwONyp7AjuRDtV59OiWMvJMQ9oWEd7iUw4uxNFswUmdQWd3OZrA9lnNq7DYbViCSZntxrO5pnBm216oYvIk22TDywdqAgj/WFut6+y32lfV2h3iLy7BrToXiD1J0wlRF/wDfBwXI+mTearHPWvjG7t0FBsMhf20LFAqjgZdewr7Is8X2DQqKAWmVlNsTJD6gXm1y0s8OXSLWoZrNDhw/cycS8vExh5F/aD7STgV3RaeYwfI2WDefY4pAaI6nXHh7lPL7JdJrvz6+7ALUY8DCkgjhY0SnlcluELBrfsMzRYUoEMq1XttHRyYDqHDPAT5QxxFbw58lLC2SRrNFli+XcIjAr8Rp68Vn9DCX3CEgUoMhCoD7L3raTK2bJwcy/bsjSWTQtfAkx7dNauMMoc4pinJPP5K3TMmczzc7KLUcVzj1DP7KVqhb1K3DqgCHqX0M2dj9EIROUa+63vwr98+uywcoT0KjlJ/lwlnONaPdXFckK2CFyXj4CNULdPoE0KyhF+GYBsM86OobGXzJ6xiozg1MSqN30qOfaKWJHkPwZwa0pE9JZAD1Z2vrn2lq+v+VBRLbekjpOJ4=

      script:
        - npm audit fix
        - npm fund
      deploy:
        provider: heroku
        app: scrume-app-s2
        strategy: git
        api_key:
          secure: CZyp19G2iOAHgiktaUK7KuIcYQshlO1Cfis4c0LvVZ/pfKvXtw7UeYTCgj8TT9VYljPEElJtzv4k6lvX8TeyX7yHvhUYni166cjkgC/xwkRADggUU6WdKNUB/OqMRaNBlI1509gmyiUFZsjLOeRf1UFSN51cOpFh/MKWTU/r3GrHJ7lUaaEYoO1+nTTiz0o6QwXTrxJBw4wnPYK+p6inL2UPNjZAUjI6VxzgUdp3LazD4xptWJaJeGWGvUH8nWYvQf1U1nLeYbLQ/cTODRjcYCGSLP42vY4zXZhJKZAIgdd5ECQxF3+7zzzfqC/pzoxQp3msB6T5857mtAED3ZeO1cz9QJLU3hxYoKuVUM7+OkmbjkgE6mQvUwfWFW0A7c9K5eSLf4Qh0dI60vVX7VpPErQHrXHVfXULS3duNvZLxlFNLmpIN98R9nHyKNWMwySM9gbaHxeqLCshkZxsmCcr1cePVuJDzk7e+p4io85M+CDVZ5OKOjObKNKw57whB3bAtWhgo6XVDCa5mn4bel/lU4iZWcpE+PGMcov47O54GhgWaA3NdW0p0XEn5UK293m+r6T3XDZQJupuekIxkpJmV/7niP+HEitw3zUWHP2Fv7adIQdzDuqQDToXW3kvE5orvzbvYdjAN4zuRnPBXcwwYucAJx2hnu2sTPMohgRewI4=
        on: 
          branch: integration2
notifications:
  email:
    on_failure: manuelc.p.g@gmail.com